### ISSUE TITLE
There is no rightful "done", "bingo_x", and "bingo_y"

### ISSUE THREAD

**Issue by bluesandwich90** [yuz835/ecc#1]
Hi, I guess the signal "done" is a flag signal for the the ecc calculation is done. But with your testbench, there is no valid "done" signal after 1428 clock cycles. Also, I guess the bingo_x and bingo_y signal will be '1' when the outputs of ECC is right. In the simulation, the bingo_x and bingo_y are always '0'. Please check it. Thank you.

**Comment by yuz835** [comment]
it's been a while, and this is actually not my final version.
I lost my hard drive, and only found this version somewhere.
but it's getting very close...

**Comment by yuz835** [comment]
also I'll check in my u-code later

**Comment by yuz835** [comment]
please take a look, 
#8d5aa0ebce7db08d4e183e46bec7e953ad38393b

you can debug from there.
Highly recommend to use software Mathematica to do the check and debug.
